  language: node_js
  node_js:
    - "12"
  services:
    - docker

  before_install:
    - npm install

  script:
    - npm run demo
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t zhnan/debit-fe:1.0.1-demo .
    - docker push zhnan/debit-fe:1.0.1-demo
